- name: "Gathering DRG details"
  oci_network_drg_facts:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    compartment_id: "{{ item.key  }}"
  loop: '{{ compartments | dict2items }}'
  register: drg_list
  loop_control:
    label: "{{ item.value }}"

- name: "creating DRG dict from json data"
  set_fact:
    drg: '{{ drg | default({}) | combine ( {item.id : [ item.display_name, item.lifecycle_state, compartments[item.compartment_id], item.compartment_id]} ) }}'
  with_items: '{{ drg_list | json_query ( "results[*].drgs[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"

- name: 'Write out CSV header for DRG'
  copy:
    content: "DRG,Compartments,State,ocid"
    dest: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/drg.csv"

- name: 'Write out CSV content for DRG'
  lineinfile:
    create: 'no'
    insertafter: 'EOF'
    line: "{{ item.display_name }},{{ compartments[item.compartment_id] }},{{ item.lifecycle_state }},{{ item.id }}"
    path: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/drg.csv"
    state: 'present'
  with_items: '{{ drg_list | json_query ( "results[*].drgs[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"
