- name: "Gathering all available compute instances in tenancy"
  oci_compute_instance_facts:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    compartment_id: "{{ item.key  }}"
  loop: '{{ compartments | dict2items }}'
  register: compute_list
  loop_control:
    label: "{{ item.value }}"

- name: "creating compute dict from json data"
  set_fact:
    compute: '{{ compute | default({}) | combine ( {item.id : [item.display_name, item.lifecycle_state, item.shape, compartments[item.compartment_id], item.primary_private_ip, item.primary_public_ip, item.region, pvtip_by_ip[item.primary_private_ip]]} ) }}'
  with_items: '{{ compute_list | json_query ( "results[*].instances[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"

- name: 'Write out CSV header for compute instances'
  copy:
    content: "Ocid,compartment,Instance,Creation-Time,Public-IP,Image-ID,Shape,Lifecycle-State,Availability-Domain,Private-IP,Hostname,Subnet,Domain"
    dest: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/compute.csv"

- name: 'Write out CSV content for compute instances'
  lineinfile:
    create: 'no'
    insertafter: 'EOF'
    line: "{{ item.id }},{{ compartments[item.compartment_id] }},{{ item.display_name }},{{ item.time_created.split('.')[0] }},{{ item.primary_public_ip }},{{ item.image_id }},{{ item.shape }},{{ item.lifecycle_state }},{{ item.availability_domain }},{{ item.primary_private_ip }},{{ pvtip_by_ip[item.primary_private_ip] | join (',') }}"
    path: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/compute.csv"
    state: 'present'
  with_items: '{{ compute_list | json_query ( "results[*].instances[*]" ) }}'
  loop_control:
    label: '{{ item.display_name }}'

