---
# tasks file for oci_collection_tenancy_facts_compute
- name: Validating role oci_collection_authenticate
  include_role:
    name: oci_collection_authenticate
  when: oci_local_username is not defined

- name: validating role  oci_collection_tenancy_facts_compandads
  include_role:
    name: oci_collection_tenancy_facts_compandads
  when: compartments is not defined

- name: validating role oci_collection_tenancy_facts_network
  include_role:
    name: oci_collection_tenancy_facts_network
  when: vcn is not defined

- name: 'Starting compute playbook'
  include_tasks: 'compute.yml'

- name: 'Starting custom images playbook'
  include_tasks: 'custom.yml'