---
# tasks file for oci_authenticate
- name: My Learning tasks
  gather_facts: "false"
  hosts: localhost
  collections:
    - 'oracle.oci'
  roles:
    - role: oci_collection_authenticate
    - role: oci_collection_tenancy_decommission_prepration
    - role: oci_collection_tenancy_decommission_compute_shutdown
