- name: "Gathering dhcp options"
  oci_network_dhcp_options_facts:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    compartment_id: "{{ item.value[1]  }}"
    vcn_id: "{{ item.key }}"
  loop: '{{ vcn | dict2items }}'
  register: dhcp_list
  loop_control:
    label: "{{ item.value[0] }}"

- name: "creating dhcp dict from json data"
  set_fact:
    dhcp: '{{ dhcp | default({}) | combine ( {item.id : [item.display_name, vcn[item.vcn_id][0]]} ) }}'
  with_items: '{{ dhcp_list | json_query ( "results[*].dhcp_options[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"

- name: 'Write out CSV header for DHCP'
  lineinfile:
    create: 'no'
    insertafter: 'EOF'
    line: "\n\nDHCP,Server-Type,Compartment,State,Creation-Time,VCN,ocid"
    path: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/network.csv"
    state: 'present'

- name: 'Write out CSV content for DHCP'
  lineinfile:
    create: 'no'
    insertafter: 'EOF'
    line: "{{ item.display_name }},{{ item.options[0].type }},{{ compartments[item.compartment_id] }},{{ item.lifecycle_state }},{{ item.time_created.split('.')[0] }},{{ vcn[item.vcn_id][0] }},{{ item.id }}"
    path: "/home/{{ oci_local_username }}/tenancy_decommision/{{ oci_tenancy + '_' + oci_datacenter }}/network.csv"
    state: 'present'
  with_items: '{{ dhcp_list | json_query ( "results[*].dhcp_options[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"
