---
# tasks file for oci_collection_tenancy_decommission_compute_shutdown
- name: These instances are ready to be shutdown.
  debug:
    var: compute

- name: Input required from user to proceed.
  pause:
    prompt: Press Ctrl + C to abort or Enter to continue.

