- name: Add 7 days to Current Date
  set_fact:
    decom_date: "{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 7 )  ) }}"

- name: show decom_date output
  debug:
   msg: "{{ decom_date }}"


###############################################COMPUTE RENAME###########################







- name: Set facts for Instance-SID
  set_fact:
    instance_sid: '{{ instance_sid | default({}) | combine ( {item.key : item.value } ) }}'
  with_items: "{{ compute | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when:  USID |upper in  item.value[0] or USID |lower in  item.value[0]


- name: show instance_sid list
  debug:
    msg: "{{ instance_sid | dict2items }}"








# #################################BLOCK VOLUME################################################

- name: show attached_blockvol_list  dict
  debug:
    msg:  '{{ attached_blockvol | dict2items }}'



- name: Set facts for Block-SID
  set_fact:
    block_sid: '{{ block_sid | default({}) | combine ( {item.key : item.value } ) }}'
  with_items: "{{ attached_blockvol | dict2items }}"
  loop_control:
    label: "{{ item.value[4] }}"
  when:  USID |upper in  item.value[4] or USID |lower in  item.value[4]

- name: show block_sid TO RENAME  dict
  debug:
    msg:  '{{ block_sid | dict2items }}'  








###################################LBAAS##############################################
- name: show lbaas output
  debug:
    msg:  '{{ lbaas | dict2items }}' 

- name: Set facts for LBAAS-SID
  set_fact:
    lbaas_sid: '{{ lbaas_sid | default({}) | combine ( {item.key : item.value } ) }}'
  with_items: "{{ lbaas | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when:  USID |upper in  item.value[0] or USID |lower in  item.value[0]

- name: show lbaas_sid TO RENAME  dict
  debug:
    msg:  '{{ lbaas_sid | dict2items }}'  








#########################################FSS#######################################

- name: Set facts for FSS-SID
  set_fact:
    fss_sid: '{{ fss_sid | default({}) | combine ( {item.key : item.value } ) }}'
  with_items: "{{ fss | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when:  USID |upper in  item.value[0] or USID |lower in  item.value[0]


- name: show FSS TO RENAME  dict
  debug:
    msg:  '{{ fss_sid | dict2items }}'  











##########################################DBAAS#######################################

- name: show DBAAS1 list output
  debug:
    msg: "{{ dbaas1 | dict2items }}"


- name: Set facts for DBAAS-SID
  set_fact:
    dbaas_sid: '{{ dbaas_sid | default({}) | combine ( {item.key : item.value} ) }}'
  with_items: "{{ dbaas1 | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when:  USID |upper in  item.value[0] or USID |lower in  item.value[0]



- name: show DBAAS-SID dictionary
  debug:
    msg: "{{ dbaas_sid | dict2items }}"




- name: "Gathering all available DB_nodes to decom and stop in tenancy for given REQUEST"
  oci_database_db_node_facts:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    compartment_id: "{{ item.value[1]  }}"
    db_system_id: "{{ item.key  }}"
  loop: '{{ dbaas_sid | dict2items }}'
  register: dbnodes_sid_list
  loop_control:
    label: "{{ item.value[0] }}"
  when: USID |upper in  item.value[0] or USID |lower in  item.value[0]

- name: show dbnodes_sid_list
  debug:
    msg: '{{ dbnodes_sid_list | json_query ( "results[*].db_nodes[*]" ) }}'





- name: "creating DBNODE-SID dict from json data"
  set_fact:
    dbnode_sid: '{{ dbnode_sid | default({}) | combine ( {item.id : [item.hostname, item.db_system_id]} ) }}'
  with_items: '{{ dbnodes_sid_list | json_query ( "results[*].db_nodes[*]" ) }}'
  loop_control:
    label: "{{ item.hostname }}"

- name: show dbnodes DICT TO USE FOR SHUTDOWN
  debug:
    msg: "{{ dbnode_sid | dict2items }}"






