# #tasks  for oci_collection_tenancy_decommission_compute Rename



- name: Input required from user to proceed for Updating and Renaming instances.
  pause:
   prompt: Press Ctrl + C to abort or Enter to continue.
  when: >
    action == 'shutdown' and
    instance_sid is defined


- name: Updating and Renaming instances
  oci_compute_instance:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    display_name: "{{ item.value[0] }}_EXPIRY_{{ decom_date }}_{{ rfc }}"
    instance_id: "{{ item.key }}"
  with_items: "{{ instance_sid | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when: >
    action == 'shutdown' and
    instance_sid is defined
  ignore_errors: yes
#tasks for oci_collection_tenancy_decommission_compute_shutdown


- name: Perform action stop on instance
  oci_compute_instance_actions:
   config_file_location: '{{ oci_local_homedir }}/.oci/config'
   config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
   instance_id: "{{ item.key }}"
   action: stop
  with_items: '{{ instance_sid | dict2items }}'
  loop_control:
   label: "{{ item.value[0] }}"
  when: >
    action == 'shutdown' and
    instance_sid is defined
  ignore_errors: yes
#tasks for oci_collection_tenancy_decommission DBAAS SHUTDOWN




- name: Input required from user to proceed for SHUTTING DOWN DB_NODE for Requested DB System.
  pause:
   prompt: Press Ctrl + C to abort or Enter to continue.
  when: >
    action == 'shutdown' and
    dbnode_sid is defined
  

- name: SHUTTING DOWN DB_NODE for Requested DB System
  oci_database_db_node_actions:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    db_node_id: "{{ item.key }}"
    action: stop
  with_items: "{{ dbnode_sid | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when: >
    action == 'shutdown' and
    dbnode_sid is defined
  ignore_errors: yes



# #tasks for oci_collection_tenancy_decommission BLOCK VOLUME



- name: Input required from user to proceed for Updating and Renaming Block Volume.
  pause:
   prompt: Press Ctrl + C to abort or Enter to continue.
  when: >
    action == 'shutdown' and
    block_sid is defined


- name: Updating and Renaming Block Volume
  oci_blockstorage_volume:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    display_name: "{{ item.value[4] }}_EXPIRY_{{ decom_date }}_{{ rfc }}"
    volume_id: "{{ item.key }}"
  with_items: "{{ block_sid | dict2items }}"
  loop_control:
    label: "{{ item.value[4] }}"
  when: >
    action == 'shutdown' and
    block_sid is defined
  ignore_errors: yes


# #tasks for oci_collection_tenancy_decommission LBAAS RENAME



- name: Input required from user to proceed for Updating and Renaming Load BALANCER.
  pause:
   prompt: Press Ctrl + C to abort or Enter to continue.
  when: >
    action == 'shutdown' and
    lbaas_sid is defined


- name: Updating and Renaming Load BALANCER
  oci_loadbalancer_load_balancer:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    display_name: "{{ item.value[0] }}_EXPIRY_{{ decom_date }}_{{ rfc }}"
    load_balancer_id: "{{ item.key }}"
  with_items: "{{ lbaas_sid | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when: >
    action == 'shutdown' and
    lbaas_sid is defined
  ignore_errors: yes

# #tasks for oci_collection_tenancy_decommission FSS RENAME



- name: Input required from user to proceed for Updating and Renaming FILE SYSTEM.
  pause:
   prompt: Press Ctrl + C to abort or Enter to continue.
  when: >
    action == 'shutdown' and
    fss_sid is defined
  

- name: Updating and Renaming FILE SYSTEM
  oci_file_storage_file_system:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    display_name: "{{ item.value[0] }}_EXPIRY_{{ decom_date }}_{{ rfc }}"
    file_system_id: "{{ item.key }}"
  with_items: "{{ fss_sid | dict2items }}"
  loop_control:
    label: "{{ item.value[0] }}"
  when: >
    action == 'shutdown' and
    fss_sid is defined
  ignore_errors: yes