- name: "Gathering all available fss details in tenancy"
  oci_file_storage_file_system_facts:
    config_file_location: '{{ oci_local_homedir }}/.oci/config'
    config_profile_name: '{{ oci_tenancy }}_{{ oci_datacenter }}'
    availability_domain: "{{ item[1].value }}"
    compartment_id: "{{ item[0].key }}"
  with_nested: 
    - '{{ compartments | dict2items }}'
    - '{{ ads | dict2items }}'
  register: fss_list
  loop_control:
    label: "{{ item[0].value, item[1].value }}"

- name: "creating FSS dict from json data"
  set_fact:
    fss: '{{ fss | default({}) | combine ( {item.id : [item.display_name, item.time_created]} ) }}'
  with_items: '{{ fss_list | json_query ( "results[*].file_systems[*]" ) }}'
  loop_control:
    label: "{{ item.display_name }}"

- name: "show fss dictionary data"
  debug:
    var=fss_list
